/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __PLATFORM_DATA_X86_ASUS_WMI_H_EXT
#define __PLATFORM_DATA_X86_ASUS_WMI_H_EXT

#define ASUS_WMI_DEVID_SCREENPAD	0x00050031
#define ASUS_WMI_DEVID_SCREENPAD_LIGHT	0x00050032

#endif	/* __PLATFORM_DATA_X86_ASUS_WMI_H_EXT */
